// Exercise library — organized by bodyRegion → muscleGroup → equipment → exercises

export type Equipment = "cable" | "barbell" | "dumbbell" | "smith" | "machine";
export type MuscleGroup = "chest" | "biceps" | "triceps" | "shoulders" | "quads" | "hamstrings" | "calves" | "glutes";
export type BodyRegion = "upper" | "lower";

export interface Exercise {
  name: string;
  defaultSets: number;
  defaultReps: number;
  defaultWeight: number;
  unit?: "lbs" | "kg";
  note?: string;
}

export const BODY_REGIONS: { id: BodyRegion; label: string }[] = [
  { id: "upper", label: "Upper Body" },
  { id: "lower", label: "Lower Body" },
];

export const MUSCLE_GROUPS: Record<BodyRegion, { id: MuscleGroup; label: string }[]> = {
  upper: [
    { id: "chest",     label: "Chest" },
    { id: "biceps",    label: "Biceps" },
    { id: "triceps",   label: "Triceps" },
    { id: "shoulders", label: "Shoulders" },
  ],
  lower: [
    { id: "quads",      label: "Quads" },
    { id: "hamstrings", label: "Hamstrings" },
    { id: "calves",     label: "Calves" },
    { id: "glutes",     label: "Glutes" },
  ],
};

export const EQUIPMENT_LABELS: Record<Equipment, string> = {
  cable:    "Cable",
  barbell:  "Barbell",
  dumbbell: "Dumbbell",
  smith:    "Smith Machine",
  machine:  "Machine",
};

export const EXERCISES: Record<MuscleGroup, Record<Equipment, Exercise[]>> = {
  // ─── CHEST ──────────────────────────────────────────────────────────────────
  chest: {
    cable: [
      { name: "Cable Chest Flye (Low to High)",       defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Cable Chest Flye (High to Low)",        defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Cable Chest Flye (Mid / Crossover)",    defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Single-Arm Cable Chest Flye",           defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Cable Chest Press",                     defaultSets: 3, defaultReps: 10, defaultWeight: 40 },
      { name: "Single-Arm Cable Chest Press",          defaultSets: 3, defaultReps: 10, defaultWeight: 25 },
      { name: "Cable Incline Flye",                    defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Cable Decline Flye",                    defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Cable Pulley Push-Up",                  defaultSets: 3, defaultReps: 10, defaultWeight: 0,  note: "Bodyweight" },
      { name: "Cable Standing Chest Squeeze Press",    defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Cable Incline Press (Rope Attachment)", defaultSets: 3, defaultReps: 10, defaultWeight: 35 },
    ],
    barbell: [
      { name: "Barbell Bench Press (Flat)",            defaultSets: 4, defaultReps: 8,  defaultWeight: 135 },
      { name: "Barbell Bench Press (Incline)",         defaultSets: 3, defaultReps: 8,  defaultWeight: 115 },
      { name: "Barbell Bench Press (Decline)",         defaultSets: 3, defaultReps: 8,  defaultWeight: 125 },
      { name: "Barbell Close-Grip Bench Press",        defaultSets: 3, defaultReps: 8,  defaultWeight: 95,  note: "Targets triceps & inner chest" },
      { name: "Barbell Wide-Grip Bench Press",         defaultSets: 3, defaultReps: 8,  defaultWeight: 115 },
      { name: "Barbell Incline Bench Press (Narrow)",  defaultSets: 3, defaultReps: 8,  defaultWeight: 95 },
      { name: "Barbell Pullover",                      defaultSets: 3, defaultReps: 12, defaultWeight: 65 },
      { name: "Barbell Floor Press",                   defaultSets: 3, defaultReps: 8,  defaultWeight: 115 },
      { name: "Barbell Squeeze Press",                 defaultSets: 3, defaultReps: 12, defaultWeight: 85 },
      { name: "Barbell JM Press",                      defaultSets: 3, defaultReps: 10, defaultWeight: 75 },
      { name: "Barbell Svend Press",                   defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
    ],
    dumbbell: [
      { name: "Dumbbell Bench Press (Flat)",           defaultSets: 3, defaultReps: 10, defaultWeight: 50 },
      { name: "Dumbbell Bench Press (Incline)",        defaultSets: 3, defaultReps: 10, defaultWeight: 40 },
      { name: "Dumbbell Bench Press (Decline)",        defaultSets: 3, defaultReps: 10, defaultWeight: 45 },
      { name: "Dumbbell Chest Flye (Flat)",            defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Dumbbell Chest Flye (Incline)",         defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Dumbbell Pullover",                     defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Single-Arm Dumbbell Press",             defaultSets: 3, defaultReps: 10, defaultWeight: 40 },
      { name: "Dumbbell Squeeze Press",                defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
      { name: "Dumbbell Around the World",             defaultSets: 3, defaultReps: 12, defaultWeight: 15 },
      { name: "Dumbbell Hex Press",                    defaultSets: 3, defaultReps: 10, defaultWeight: 30 },
      { name: "Dumbbell Incline Flye (Neutral Grip)",  defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
    ],
    smith: [
      { name: "Smith Machine Bench Press (Flat)",      defaultSets: 4, defaultReps: 8,  defaultWeight: 135 },
      { name: "Smith Machine Bench Press (Incline)",   defaultSets: 3, defaultReps: 8,  defaultWeight: 115 },
      { name: "Smith Machine Bench Press (Decline)",   defaultSets: 3, defaultReps: 8,  defaultWeight: 125 },
      { name: "Smith Machine Close-Grip Bench Press",  defaultSets: 3, defaultReps: 10, defaultWeight: 95 },
      { name: "Smith Machine Wide-Grip Bench Press",   defaultSets: 3, defaultReps: 8,  defaultWeight: 115 },
      { name: "Smith Machine Incline Press (Narrow)",  defaultSets: 3, defaultReps: 10, defaultWeight: 95 },
      { name: "Smith Machine Decline Press",           defaultSets: 3, defaultReps: 8,  defaultWeight: 115 },
      { name: "Smith Machine Floor Press",             defaultSets: 3, defaultReps: 10, defaultWeight: 95 },
      { name: "Smith Machine Reverse-Grip Press",      defaultSets: 3, defaultReps: 10, defaultWeight: 85 },
      { name: "Smith Machine Svend Press",             defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Smith Machine Incline Flye-Press",      defaultSets: 3, defaultReps: 12, defaultWeight: 65 },
    ],
    machine: [
      { name: "Chest Press Machine",                   defaultSets: 3, defaultReps: 10, defaultWeight: 100 },
      { name: "Incline Chest Press Machine",           defaultSets: 3, defaultReps: 10, defaultWeight: 90 },
      { name: "Decline Chest Press Machine",           defaultSets: 3, defaultReps: 10, defaultWeight: 100 },
      { name: "Pec Deck Flye Machine",                 defaultSets: 3, defaultReps: 12, defaultWeight: 80 },
      { name: "Seated Chest Flye Machine",             defaultSets: 3, defaultReps: 12, defaultWeight: 70 },
      { name: "Plate-Loaded Chest Press",              defaultSets: 3, defaultReps: 8,  defaultWeight: 90 },
      { name: "Converging Chest Press Machine",        defaultSets: 3, defaultReps: 10, defaultWeight: 90 },
      { name: "Machine Push-Up (Assisted)",            defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Lever Pec Deck (Rear)",                 defaultSets: 3, defaultReps: 12, defaultWeight: 60 },
      { name: "Machine Incline Flye",                  defaultSets: 3, defaultReps: 12, defaultWeight: 70 },
      { name: "Machine Chest Squeeze Press",           defaultSets: 3, defaultReps: 12, defaultWeight: 80 },
    ],
  },

  // ─── BICEPS ─────────────────────────────────────────────────────────────────
  biceps: {
    cable: [
      { name: "Cable Curl (Bar)",                      defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Cable Curl (Rope)",                     defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Cable Hammer Curl (Rope)",              defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Single-Arm Cable Curl",                 defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Cable Preacher Curl",                   defaultSets: 3, defaultReps: 10, defaultWeight: 35 },
      { name: "Cable Reverse Curl",                    defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
      { name: "Overhead Cable Curl",                   defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Cable Concentration Curl",              defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "High Cable Curl (Both Arms)",           defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Cable Incline Curl",                    defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Cable Drag Curl",                       defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
    ],
    barbell: [
      { name: "Barbell Curl (Standing)",               defaultSets: 4, defaultReps: 10, defaultWeight: 65 },
      { name: "Barbell Curl (Narrow Grip)",            defaultSets: 3, defaultReps: 10, defaultWeight: 55 },
      { name: "Barbell Curl (Wide Grip)",              defaultSets: 3, defaultReps: 10, defaultWeight: 55 },
      { name: "Barbell Reverse Curl",                  defaultSets: 3, defaultReps: 12, defaultWeight: 45 },
      { name: "EZ-Bar Curl",                           defaultSets: 3, defaultReps: 10, defaultWeight: 55 },
      { name: "EZ-Bar Preacher Curl",                  defaultSets: 3, defaultReps: 10, defaultWeight: 45 },
      { name: "EZ-Bar Reverse Curl",                   defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
      { name: "Barbell Preacher Curl",                 defaultSets: 3, defaultReps: 10, defaultWeight: 55 },
      { name: "Barbell 21s",                           defaultSets: 3, defaultReps: 21, defaultWeight: 45,  note: "7 lower / 7 upper / 7 full" },
      { name: "Barbell Drag Curl",                     defaultSets: 3, defaultReps: 12, defaultWeight: 55 },
      { name: "Barbell Spider Curl",                   defaultSets: 3, defaultReps: 12, defaultWeight: 45 },
    ],
    dumbbell: [
      { name: "Dumbbell Curl (Standing, Alternating)", defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Dumbbell Curl (Both Arms)",             defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Dumbbell Hammer Curl",                  defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Dumbbell Incline Curl",                 defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Dumbbell Concentration Curl",           defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Dumbbell Preacher Curl",                defaultSets: 3, defaultReps: 10, defaultWeight: 20 },
      { name: "Dumbbell Reverse Curl",                 defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Dumbbell Spider Curl",                  defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Dumbbell Zottman Curl",                 defaultSets: 3, defaultReps: 10, defaultWeight: 20 },
      { name: "Dumbbell Cross-Body Hammer Curl",       defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Dumbbell Drag Curl",                    defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
    ],
    smith: [
      { name: "Smith Machine Curl (Standing)",         defaultSets: 3, defaultReps: 12, defaultWeight: 55 },
      { name: "Smith Machine Drag Curl",               defaultSets: 3, defaultReps: 12, defaultWeight: 45 },
      { name: "Smith Machine Preacher Curl",           defaultSets: 3, defaultReps: 10, defaultWeight: 45 },
      { name: "Smith Machine Reverse Curl",            defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
      { name: "Smith Machine Spider Curl",             defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
      { name: "Smith Machine Narrow Grip Curl",        defaultSets: 3, defaultReps: 12, defaultWeight: 45 },
      { name: "Smith Machine Wide Grip Curl",          defaultSets: 3, defaultReps: 12, defaultWeight: 45 },
      { name: "Smith Machine Incline Curl",            defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
      { name: "Smith Machine Concentration Curl",      defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Smith Machine 21s",                     defaultSets: 3, defaultReps: 21, defaultWeight: 35 },
    ],
    machine: [
      { name: "Machine Preacher Curl",                 defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Machine Bicep Curl (Seated)",           defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Machine Hammer Curl",                   defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Machine Reverse Curl",                  defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
      { name: "Assisted Pull-Up Machine (Underhand)",  defaultSets: 3, defaultReps: 8,  defaultWeight: 50 },
      { name: "Assisted Chin-Up Machine",              defaultSets: 3, defaultReps: 8,  defaultWeight: 50 },
      { name: "Machine Concentration Curl",            defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
      { name: "Machine Low Pulley Curl",               defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Lever Bicep Curl Machine",              defaultSets: 3, defaultReps: 12, defaultWeight: 45 },
      { name: "Machine Spider Curl",                   defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
    ],
  },

  // ─── TRICEPS ─────────────────────────────────────────────────────────────────
  triceps: {
    cable: [
      { name: "Cable Triceps Pushdown (Bar)",          defaultSets: 3, defaultReps: 12, defaultWeight: 60 },
      { name: "Cable Triceps Pushdown (Rope)",         defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Cable Triceps Pushdown (V-Bar)",        defaultSets: 3, defaultReps: 12, defaultWeight: 55 },
      { name: "Cable Overhead Triceps Extension",      defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Cable Overhead Triceps Extension (Rope)", defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
      { name: "Cable Kickback",                        defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Single-Arm Cable Pushdown",             defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Single-Arm Cable Overhead Extension",   defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Cable Reverse Pushdown",                defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Cable Tate Press",                      defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Cable Close-Grip Pushdown",             defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
    ],
    barbell: [
      { name: "Barbell Skull Crusher (Flat)",          defaultSets: 3, defaultReps: 10, defaultWeight: 65 },
      { name: "Barbell Skull Crusher (Incline)",       defaultSets: 3, defaultReps: 10, defaultWeight: 55 },
      { name: "Barbell Skull Crusher (Decline)",       defaultSets: 3, defaultReps: 10, defaultWeight: 65 },
      { name: "EZ-Bar Skull Crusher",                  defaultSets: 3, defaultReps: 10, defaultWeight: 55 },
      { name: "Close-Grip Bench Press",                defaultSets: 3, defaultReps: 8,  defaultWeight: 95 },
      { name: "Barbell Overhead Triceps Extension",    defaultSets: 3, defaultReps: 12, defaultWeight: 55 },
      { name: "Barbell JM Press",                      defaultSets: 3, defaultReps: 10, defaultWeight: 75 },
      { name: "Barbell Triceps Kickback",              defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Barbell Tate Press",                    defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Barbell Rolling Extension",             defaultSets: 3, defaultReps: 10, defaultWeight: 55 },
      { name: "EZ-Bar Overhead Extension (Seated)",    defaultSets: 3, defaultReps: 12, defaultWeight: 45 },
    ],
    dumbbell: [
      { name: "Dumbbell Skull Crusher",                defaultSets: 3, defaultReps: 10, defaultWeight: 25 },
      { name: "Dumbbell Overhead Extension (Both)",    defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Dumbbell Overhead Extension (Single)",  defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Dumbbell Kickback",                     defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Dumbbell Tate Press",                   defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Dumbbell Close-Grip Press",             defaultSets: 3, defaultReps: 10, defaultWeight: 35 },
      { name: "Dumbbell JM Press",                     defaultSets: 3, defaultReps: 10, defaultWeight: 25 },
      { name: "Dumbbell Triceps Rollback",             defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Dumbbell Lying Triceps Extension",      defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Dumbbell Single-Arm Kickback",          defaultSets: 3, defaultReps: 12, defaultWeight: 15 },
      { name: "Dumbbell Incline Skull Crusher",        defaultSets: 3, defaultReps: 10, defaultWeight: 20 },
    ],
    smith: [
      { name: "Smith Machine Skull Crusher",           defaultSets: 3, defaultReps: 10, defaultWeight: 65 },
      { name: "Smith Machine Close-Grip Bench Press",  defaultSets: 3, defaultReps: 8,  defaultWeight: 95 },
      { name: "Smith Machine JM Press",                defaultSets: 3, defaultReps: 10, defaultWeight: 65 },
      { name: "Smith Machine Overhead Extension",      defaultSets: 3, defaultReps: 12, defaultWeight: 55 },
      { name: "Smith Machine Tate Press",              defaultSets: 3, defaultReps: 12, defaultWeight: 45 },
      { name: "Smith Machine Incline Skull Crusher",   defaultSets: 3, defaultReps: 10, defaultWeight: 55 },
      { name: "Smith Machine Decline Skull Crusher",   defaultSets: 3, defaultReps: 10, defaultWeight: 65 },
      { name: "Smith Machine Narrow Press",            defaultSets: 3, defaultReps: 10, defaultWeight: 85 },
      { name: "Smith Machine Floor Skull Crusher",     defaultSets: 3, defaultReps: 10, defaultWeight: 55 },
      { name: "Smith Machine Reverse-Grip Pushdown",   defaultSets: 3, defaultReps: 12, defaultWeight: 45 },
    ],
    machine: [
      { name: "Triceps Dip Machine",                   defaultSets: 3, defaultReps: 10, defaultWeight: 80 },
      { name: "Triceps Extension Machine (Seated)",    defaultSets: 3, defaultReps: 12, defaultWeight: 70 },
      { name: "Triceps Pressdown Machine",             defaultSets: 3, defaultReps: 12, defaultWeight: 60 },
      { name: "Plate-Loaded Triceps Extension",        defaultSets: 3, defaultReps: 10, defaultWeight: 70 },
      { name: "Assisted Dip Machine",                  defaultSets: 3, defaultReps: 10, defaultWeight: 50 },
      { name: "Overhead Triceps Machine",              defaultSets: 3, defaultReps: 12, defaultWeight: 60 },
      { name: "Machine Triceps Kickback",              defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Machine Reverse Pushdown",              defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Leverage Triceps Extension",            defaultSets: 3, defaultReps: 12, defaultWeight: 60 },
      { name: "Bench Dip (Bodyweight)",                defaultSets: 3, defaultReps: 12, defaultWeight: 0,  note: "Bodyweight" },
    ],
  },

  // ─── SHOULDERS ───────────────────────────────────────────────────────────────
  shoulders: {
    cable: [
      { name: "Cable Lateral Raise",                   defaultSets: 3, defaultReps: 15, defaultWeight: 15 },
      { name: "Cable Leaning Lateral Raise",           defaultSets: 3, defaultReps: 15, defaultWeight: 15 },
      { name: "Single-Arm Cable Lateral Raise",        defaultSets: 3, defaultReps: 15, defaultWeight: 12 },
      { name: "Cable Front Raise",                     defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Cable Upright Row",                     defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Cable Rear Delt Flye",                  defaultSets: 3, defaultReps: 15, defaultWeight: 15 },
      { name: "Cable Face Pull (Rope)",                defaultSets: 3, defaultReps: 15, defaultWeight: 30 },
      { name: "Cable Overhead Press",                  defaultSets: 3, defaultReps: 10, defaultWeight: 30 },
      { name: "Cable Shoulder Press (Seated)",         defaultSets: 3, defaultReps: 10, defaultWeight: 25 },
      { name: "Cable Arnold Press",                    defaultSets: 3, defaultReps: 10, defaultWeight: 20 },
      { name: "Cable Reverse Flye",                    defaultSets: 3, defaultReps: 15, defaultWeight: 15 },
    ],
    barbell: [
      { name: "Barbell Overhead Press (Standing)",     defaultSets: 4, defaultReps: 8,  defaultWeight: 95 },
      { name: "Barbell Overhead Press (Seated)",       defaultSets: 3, defaultReps: 8,  defaultWeight: 85 },
      { name: "Barbell Push Press",                    defaultSets: 3, defaultReps: 6,  defaultWeight: 115 },
      { name: "Barbell Upright Row",                   defaultSets: 3, defaultReps: 12, defaultWeight: 65 },
      { name: "Barbell Front Raise",                   defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
      { name: "Barbell Shrug",                         defaultSets: 3, defaultReps: 12, defaultWeight: 135 },
      { name: "Barbell Behind-the-Neck Press",         defaultSets: 3, defaultReps: 10, defaultWeight: 75 },
      { name: "Barbell Z-Press",                       defaultSets: 3, defaultReps: 10, defaultWeight: 65 },
      { name: "Barbell High Pull",                     defaultSets: 3, defaultReps: 8,  defaultWeight: 95 },
      { name: "Barbell Bradford Press",                defaultSets: 3, defaultReps: 10, defaultWeight: 55 },
      { name: "Barbell Snatch-Grip Press",             defaultSets: 3, defaultReps: 10, defaultWeight: 65 },
    ],
    dumbbell: [
      { name: "Dumbbell Shoulder Press (Seated)",      defaultSets: 3, defaultReps: 10, defaultWeight: 35 },
      { name: "Dumbbell Shoulder Press (Standing)",    defaultSets: 3, defaultReps: 10, defaultWeight: 30 },
      { name: "Dumbbell Arnold Press",                 defaultSets: 3, defaultReps: 10, defaultWeight: 25 },
      { name: "Dumbbell Lateral Raise",                defaultSets: 3, defaultReps: 15, defaultWeight: 15 },
      { name: "Dumbbell Front Raise",                  defaultSets: 3, defaultReps: 12, defaultWeight: 15 },
      { name: "Dumbbell Rear Delt Flye",               defaultSets: 3, defaultReps: 15, defaultWeight: 15 },
      { name: "Dumbbell Upright Row",                  defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Dumbbell Shrug",                        defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Dumbbell Y-Press",                      defaultSets: 3, defaultReps: 12, defaultWeight: 15 },
      { name: "Dumbbell Incline Lateral Raise",        defaultSets: 3, defaultReps: 15, defaultWeight: 12 },
      { name: "Dumbbell Bent-Over Rear Delt Raise",    defaultSets: 3, defaultReps: 15, defaultWeight: 15 },
    ],
    smith: [
      { name: "Smith Machine Shoulder Press (Seated)", defaultSets: 3, defaultReps: 8,  defaultWeight: 85 },
      { name: "Smith Machine Shoulder Press (Standing)", defaultSets: 3, defaultReps: 8, defaultWeight: 85 },
      { name: "Smith Machine Behind-the-Neck Press",   defaultSets: 3, defaultReps: 10, defaultWeight: 75 },
      { name: "Smith Machine Upright Row",             defaultSets: 3, defaultReps: 12, defaultWeight: 55 },
      { name: "Smith Machine Shrug",                   defaultSets: 3, defaultReps: 12, defaultWeight: 135 },
      { name: "Smith Machine Push Press",              defaultSets: 3, defaultReps: 6,  defaultWeight: 95 },
      { name: "Smith Machine Bradford Press",          defaultSets: 3, defaultReps: 10, defaultWeight: 55 },
      { name: "Smith Machine Z-Press",                 defaultSets: 3, defaultReps: 10, defaultWeight: 65 },
      { name: "Smith Machine Front Raise",             defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
      { name: "Smith Machine Lateral Raise",           defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
    ],
    machine: [
      { name: "Shoulder Press Machine (Seated)",       defaultSets: 3, defaultReps: 10, defaultWeight: 80 },
      { name: "Lateral Raise Machine",                 defaultSets: 3, defaultReps: 15, defaultWeight: 40 },
      { name: "Rear Delt Fly Machine",                 defaultSets: 3, defaultReps: 15, defaultWeight: 50 },
      { name: "Shoulder Shrug Machine",                defaultSets: 3, defaultReps: 12, defaultWeight: 100 },
      { name: "Plate-Loaded Shoulder Press",           defaultSets: 3, defaultReps: 8,  defaultWeight: 90 },
      { name: "Machine Upright Row",                   defaultSets: 3, defaultReps: 12, defaultWeight: 60 },
      { name: "Machine Face Pull",                     defaultSets: 3, defaultReps: 15, defaultWeight: 50 },
      { name: "Machine Front Raise",                   defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Lever Shoulder Press",                  defaultSets: 3, defaultReps: 10, defaultWeight: 70 },
      { name: "Seated Row (High / Rear Delt)",         defaultSets: 3, defaultReps: 15, defaultWeight: 60 },
      { name: "Machine Arnold Press",                  defaultSets: 3, defaultReps: 10, defaultWeight: 60 },
    ],
  },

  // ─── QUADS ───────────────────────────────────────────────────────────────────
  quads: {
    cable: [
      { name: "Cable Leg Extension",                   defaultSets: 3, defaultReps: 15, defaultWeight: 40 },
      { name: "Cable Squat",                           defaultSets: 3, defaultReps: 12, defaultWeight: 60 },
      { name: "Cable Front Squat",                     defaultSets: 3, defaultReps: 10, defaultWeight: 50 },
      { name: "Cable Split Squat",                     defaultSets: 3, defaultReps: 10, defaultWeight: 40 },
      { name: "Cable Reverse Lunge",                   defaultSets: 3, defaultReps: 10, defaultWeight: 30 },
      { name: "Cable Forward Lunge",                   defaultSets: 3, defaultReps: 10, defaultWeight: 30 },
      { name: "Cable Step-Up",                         defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Cable Sissy Squat",                     defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Cable Terminal Knee Extension",         defaultSets: 3, defaultReps: 15, defaultWeight: 20 },
      { name: "Cable Single-Leg Extension",            defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
    ],
    barbell: [
      { name: "Barbell Back Squat",                    defaultSets: 4, defaultReps: 8,  defaultWeight: 185 },
      { name: "Barbell Front Squat",                   defaultSets: 3, defaultReps: 6,  defaultWeight: 135 },
      { name: "Barbell Pause Squat",                   defaultSets: 3, defaultReps: 6,  defaultWeight: 155 },
      { name: "Barbell Box Squat",                     defaultSets: 3, defaultReps: 6,  defaultWeight: 165 },
      { name: "Barbell Hack Squat",                    defaultSets: 3, defaultReps: 8,  defaultWeight: 135 },
      { name: "Barbell Lunge (Walking)",               defaultSets: 3, defaultReps: 10, defaultWeight: 95 },
      { name: "Barbell Lunge (Stationary)",            defaultSets: 3, defaultReps: 10, defaultWeight: 95 },
      { name: "Barbell Bulgarian Split Squat",         defaultSets: 3, defaultReps: 8,  defaultWeight: 65 },
      { name: "Barbell Step-Up",                       defaultSets: 3, defaultReps: 10, defaultWeight: 95 },
      { name: "Barbell Sissy Squat",                   defaultSets: 3, defaultReps: 12, defaultWeight: 45 },
      { name: "Barbell Zercher Squat",                 defaultSets: 3, defaultReps: 8,  defaultWeight: 115 },
    ],
    dumbbell: [
      { name: "Dumbbell Goblet Squat",                 defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Dumbbell Bulgarian Split Squat",        defaultSets: 3, defaultReps: 10, defaultWeight: 35 },
      { name: "Dumbbell Lunge (Walking)",              defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Dumbbell Lunge (Stationary)",           defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Dumbbell Step-Up",                      defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Dumbbell Front Squat",                  defaultSets: 3, defaultReps: 10, defaultWeight: 40 },
      { name: "Dumbbell Sumo Squat",                   defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Dumbbell Box Squat",                    defaultSets: 3, defaultReps: 10, defaultWeight: 40 },
      { name: "Dumbbell Reverse Lunge",                defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Dumbbell Sissy Squat",                  defaultSets: 3, defaultReps: 12, defaultWeight: 0,  note: "Bodyweight / hold plate" },
      { name: "Dumbbell Curtsy Lunge",                 defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
    ],
    smith: [
      { name: "Smith Machine Back Squat",              defaultSets: 4, defaultReps: 8,  defaultWeight: 185 },
      { name: "Smith Machine Front Squat",             defaultSets: 3, defaultReps: 8,  defaultWeight: 135 },
      { name: "Smith Machine Split Squat",             defaultSets: 3, defaultReps: 10, defaultWeight: 95 },
      { name: "Smith Machine Lunge",                   defaultSets: 3, defaultReps: 10, defaultWeight: 95 },
      { name: "Smith Machine Bulgarian Split Squat",   defaultSets: 3, defaultReps: 10, defaultWeight: 75 },
      { name: "Smith Machine Hack Squat",              defaultSets: 3, defaultReps: 8,  defaultWeight: 135 },
      { name: "Smith Machine Box Squat",               defaultSets: 3, defaultReps: 8,  defaultWeight: 155 },
      { name: "Smith Machine Step-Up",                 defaultSets: 3, defaultReps: 12, defaultWeight: 95 },
      { name: "Smith Machine Sissy Squat",             defaultSets: 3, defaultReps: 12, defaultWeight: 65 },
      { name: "Smith Machine Pause Squat",             defaultSets: 3, defaultReps: 6,  defaultWeight: 155 },
    ],
    machine: [
      { name: "Leg Extension Machine",                 defaultSets: 3, defaultReps: 12, defaultWeight: 120 },
      { name: "Leg Press (Standard)",                  defaultSets: 4, defaultReps: 10, defaultWeight: 200 },
      { name: "Leg Press (Narrow Stance)",             defaultSets: 3, defaultReps: 10, defaultWeight: 180 },
      { name: "Leg Press (Wide Stance)",               defaultSets: 3, defaultReps: 10, defaultWeight: 200 },
      { name: "Hack Squat Machine",                    defaultSets: 3, defaultReps: 8,  defaultWeight: 160 },
      { name: "Pendulum Squat Machine",                defaultSets: 3, defaultReps: 10, defaultWeight: 140 },
      { name: "Laying Leg Press",                      defaultSets: 3, defaultReps: 12, defaultWeight: 180 },
      { name: "Single-Leg Press Machine",              defaultSets: 3, defaultReps: 12, defaultWeight: 100 },
      { name: "V-Squat Machine",                       defaultSets: 3, defaultReps: 10, defaultWeight: 150 },
      { name: "Belt Squat Machine",                    defaultSets: 3, defaultReps: 10, defaultWeight: 140 },
    ],
  },

  // ─── HAMSTRINGS ──────────────────────────────────────────────────────────────
  hamstrings: {
    cable: [
      { name: "Cable Leg Curl (Standing)",             defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Cable Leg Curl (Kneeling)",             defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Cable Romanian Deadlift",               defaultSets: 3, defaultReps: 10, defaultWeight: 60 },
      { name: "Cable Pull-Through",                    defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Cable Good Morning",                    defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Cable Hip Hinge",                       defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Cable Straight-Leg Deadlift",           defaultSets: 3, defaultReps: 10, defaultWeight: 50 },
      { name: "Cable Donkey Kick",                     defaultSets: 3, defaultReps: 15, defaultWeight: 20 },
      { name: "Cable Single-Leg Curl",                 defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Cable Seated Leg Curl",                 defaultSets: 3, defaultReps: 12, defaultWeight: 35 },
    ],
    barbell: [
      { name: "Barbell Romanian Deadlift",             defaultSets: 4, defaultReps: 8,  defaultWeight: 155 },
      { name: "Barbell Conventional Deadlift",         defaultSets: 4, defaultReps: 5,  defaultWeight: 225 },
      { name: "Barbell Sumo Deadlift",                 defaultSets: 3, defaultReps: 5,  defaultWeight: 225 },
      { name: "Barbell Stiff-Leg Deadlift",            defaultSets: 3, defaultReps: 8,  defaultWeight: 155 },
      { name: "Barbell Good Morning",                  defaultSets: 3, defaultReps: 10, defaultWeight: 95 },
      { name: "Barbell Nordic Hamstring Curl",         defaultSets: 3, defaultReps: 6,  defaultWeight: 0, note: "Bodyweight" },
      { name: "Barbell Glute-Ham Raise",               defaultSets: 3, defaultReps: 8,  defaultWeight: 0, note: "Bodyweight" },
      { name: "Barbell Hip Hinge",                     defaultSets: 3, defaultReps: 10, defaultWeight: 115 },
      { name: "Barbell Single-Leg RDL",                defaultSets: 3, defaultReps: 8,  defaultWeight: 65 },
      { name: "Barbell Snatch-Grip Deadlift",          defaultSets: 3, defaultReps: 5,  defaultWeight: 155 },
    ],
    dumbbell: [
      { name: "Dumbbell Romanian Deadlift",            defaultSets: 3, defaultReps: 10, defaultWeight: 50 },
      { name: "Dumbbell Single-Leg RDL",               defaultSets: 3, defaultReps: 10, defaultWeight: 35 },
      { name: "Dumbbell Stiff-Leg Deadlift",           defaultSets: 3, defaultReps: 10, defaultWeight: 45 },
      { name: "Dumbbell Good Morning",                 defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Dumbbell Sumo Deadlift",                defaultSets: 3, defaultReps: 10, defaultWeight: 60 },
      { name: "Dumbbell Lying Leg Curl",               defaultSets: 3, defaultReps: 12, defaultWeight: 25 },
      { name: "Dumbbell Nordic Hamstring Curl",        defaultSets: 3, defaultReps: 8,  defaultWeight: 0, note: "Bodyweight" },
      { name: "Dumbbell Hip Hinge (Hinged Back)",      defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Dumbbell Glute-Ham Raise",              defaultSets: 3, defaultReps: 8,  defaultWeight: 0, note: "Bodyweight" },
      { name: "Dumbbell Kickback (Hip Hinge)",         defaultSets: 3, defaultReps: 15, defaultWeight: 15 },
    ],
    smith: [
      { name: "Smith Machine Romanian Deadlift",       defaultSets: 3, defaultReps: 10, defaultWeight: 155 },
      { name: "Smith Machine Stiff-Leg Deadlift",      defaultSets: 3, defaultReps: 10, defaultWeight: 135 },
      { name: "Smith Machine Good Morning",            defaultSets: 3, defaultReps: 10, defaultWeight: 95 },
      { name: "Smith Machine Single-Leg RDL",          defaultSets: 3, defaultReps: 10, defaultWeight: 65 },
      { name: "Smith Machine Sumo Deadlift",           defaultSets: 3, defaultReps: 8,  defaultWeight: 185 },
      { name: "Smith Machine Hip Hinge",               defaultSets: 3, defaultReps: 12, defaultWeight: 115 },
      { name: "Smith Machine Lying Leg Curl",          defaultSets: 3, defaultReps: 12, defaultWeight: 45 },
      { name: "Smith Machine Glute-Ham Raise",         defaultSets: 3, defaultReps: 8,  defaultWeight: 0, note: "Bodyweight" },
      { name: "Smith Machine Snatch-Grip Deadlift",    defaultSets: 3, defaultReps: 6,  defaultWeight: 135 },
      { name: "Smith Machine Pause RDL",               defaultSets: 3, defaultReps: 8,  defaultWeight: 115 },
    ],
    machine: [
      { name: "Lying Leg Curl Machine",                defaultSets: 3, defaultReps: 12, defaultWeight: 80 },
      { name: "Seated Leg Curl Machine",               defaultSets: 3, defaultReps: 12, defaultWeight: 90 },
      { name: "Standing Leg Curl Machine",             defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Nordic Hamstring Machine",              defaultSets: 3, defaultReps: 8,  defaultWeight: 0, note: "Bodyweight" },
      { name: "Glute-Ham Raise Machine",               defaultSets: 3, defaultReps: 8,  defaultWeight: 0, note: "Bodyweight" },
      { name: "Leg Press (Feet High / Wide)",          defaultSets: 3, defaultReps: 10, defaultWeight: 180 },
      { name: "Single-Leg Curl Machine",               defaultSets: 3, defaultReps: 12, defaultWeight: 40 },
      { name: "Hip Extension Machine",                 defaultSets: 3, defaultReps: 15, defaultWeight: 60 },
      { name: "Reverse Hyper Machine",                 defaultSets: 3, defaultReps: 15, defaultWeight: 50 },
      { name: "45° Back Extension Machine",            defaultSets: 3, defaultReps: 15, defaultWeight: 0, note: "Bodyweight" },
    ],
  },

  // ─── CALVES ──────────────────────────────────────────────────────────────────
  calves: {
    cable: [
      { name: "Cable Standing Calf Raise",             defaultSets: 4, defaultReps: 15, defaultWeight: 50 },
      { name: "Cable Single-Leg Calf Raise",           defaultSets: 3, defaultReps: 15, defaultWeight: 30 },
      { name: "Cable Seated Calf Raise",               defaultSets: 3, defaultReps: 15, defaultWeight: 40 },
      { name: "Cable Donkey Calf Raise",               defaultSets: 3, defaultReps: 15, defaultWeight: 40 },
      { name: "Cable Tibialis Raise",                  defaultSets: 3, defaultReps: 15, defaultWeight: 20 },
      { name: "Cable Ankle Dorsiflexion",              defaultSets: 3, defaultReps: 15, defaultWeight: 15 },
      { name: "Cable Soleus Press",                    defaultSets: 3, defaultReps: 20, defaultWeight: 30 },
      { name: "Cable Reverse Calf Raise",              defaultSets: 3, defaultReps: 15, defaultWeight: 20 },
      { name: "Cable Calf Raise (Toes In)",            defaultSets: 3, defaultReps: 15, defaultWeight: 40 },
      { name: "Cable Calf Raise (Toes Out)",           defaultSets: 3, defaultReps: 15, defaultWeight: 40 },
    ],
    barbell: [
      { name: "Barbell Standing Calf Raise",           defaultSets: 4, defaultReps: 15, defaultWeight: 95 },
      { name: "Barbell Single-Leg Calf Raise",         defaultSets: 3, defaultReps: 15, defaultWeight: 65 },
      { name: "Barbell Seated Calf Raise",             defaultSets: 3, defaultReps: 20, defaultWeight: 65 },
      { name: "Barbell Donkey Calf Raise",             defaultSets: 3, defaultReps: 15, defaultWeight: 95 },
      { name: "Barbell Calf Raise (Toes In)",          defaultSets: 3, defaultReps: 15, defaultWeight: 85 },
      { name: "Barbell Calf Raise (Toes Out)",         defaultSets: 3, defaultReps: 15, defaultWeight: 85 },
      { name: "Barbell Jump Calf Raise",               defaultSets: 3, defaultReps: 15, defaultWeight: 65 },
      { name: "Barbell Calf Raise (Pause at Bottom)",  defaultSets: 3, defaultReps: 12, defaultWeight: 85 },
      { name: "Barbell Tibialis Raise",                defaultSets: 3, defaultReps: 15, defaultWeight: 45 },
      { name: "Barbell Hack Calf Raise",               defaultSets: 3, defaultReps: 15, defaultWeight: 85 },
    ],
    dumbbell: [
      { name: "Dumbbell Standing Calf Raise",          defaultSets: 4, defaultReps: 15, defaultWeight: 50 },
      { name: "Dumbbell Single-Leg Calf Raise",        defaultSets: 3, defaultReps: 15, defaultWeight: 35 },
      { name: "Dumbbell Seated Calf Raise",            defaultSets: 3, defaultReps: 20, defaultWeight: 35 },
      { name: "Dumbbell Donkey Calf Raise",            defaultSets: 3, defaultReps: 15, defaultWeight: 40 },
      { name: "Dumbbell Calf Raise (Toes In)",         defaultSets: 3, defaultReps: 15, defaultWeight: 45 },
      { name: "Dumbbell Calf Raise (Toes Out)",        defaultSets: 3, defaultReps: 15, defaultWeight: 45 },
      { name: "Dumbbell Step Calf Raise",              defaultSets: 3, defaultReps: 15, defaultWeight: 35 },
      { name: "Dumbbell Jump Calf Raise",              defaultSets: 3, defaultReps: 15, defaultWeight: 20 },
      { name: "Dumbbell Tibialis Raise",               defaultSets: 3, defaultReps: 15, defaultWeight: 20 },
      { name: "Dumbbell Eccentric Calf Raise",         defaultSets: 3, defaultReps: 10, defaultWeight: 40, note: "Slow 4s descent" },
    ],
    smith: [
      { name: "Smith Machine Calf Raise (Standing)",   defaultSets: 4, defaultReps: 15, defaultWeight: 95 },
      { name: "Smith Machine Calf Raise (Seated)",     defaultSets: 3, defaultReps: 20, defaultWeight: 65 },
      { name: "Smith Machine Single-Leg Calf Raise",   defaultSets: 3, defaultReps: 15, defaultWeight: 65 },
      { name: "Smith Machine Donkey Calf Raise",       defaultSets: 3, defaultReps: 15, defaultWeight: 95 },
      { name: "Smith Machine Calf Raise (Toes In)",    defaultSets: 3, defaultReps: 15, defaultWeight: 85 },
      { name: "Smith Machine Calf Raise (Toes Out)",   defaultSets: 3, defaultReps: 15, defaultWeight: 85 },
      { name: "Smith Machine Jump Calf Raise",         defaultSets: 3, defaultReps: 15, defaultWeight: 65 },
      { name: "Smith Machine Tibialis Raise",          defaultSets: 3, defaultReps: 15, defaultWeight: 35 },
      { name: "Smith Machine Pause Calf Raise",        defaultSets: 3, defaultReps: 12, defaultWeight: 85 },
      { name: "Smith Machine Calf Raise (Wide)",       defaultSets: 3, defaultReps: 15, defaultWeight: 85 },
    ],
    machine: [
      { name: "Standing Calf Raise Machine",           defaultSets: 4, defaultReps: 15, defaultWeight: 120 },
      { name: "Seated Calf Raise Machine",             defaultSets: 3, defaultReps: 20, defaultWeight: 80 },
      { name: "Donkey Calf Raise Machine",             defaultSets: 3, defaultReps: 15, defaultWeight: 100 },
      { name: "Leg Press Calf Raise",                  defaultSets: 3, defaultReps: 20, defaultWeight: 160 },
      { name: "Single-Leg Calf Raise Machine",         defaultSets: 3, defaultReps: 15, defaultWeight: 60 },
      { name: "Calf Raise Machine (Toes In)",          defaultSets: 3, defaultReps: 15, defaultWeight: 100 },
      { name: "Calf Raise Machine (Toes Out)",         defaultSets: 3, defaultReps: 15, defaultWeight: 100 },
      { name: "Tibialis Raise Machine",                defaultSets: 3, defaultReps: 15, defaultWeight: 40 },
      { name: "Hack Squat Calf Press",                 defaultSets: 3, defaultReps: 15, defaultWeight: 120 },
      { name: "Machine Eccentric Calf Raise",          defaultSets: 3, defaultReps: 10, defaultWeight: 80, note: "Slow 4s descent" },
    ],
  },

  // ─── GLUTES ──────────────────────────────────────────────────────────────────
  glutes: {
    cable: [
      { name: "Cable Kickback",                        defaultSets: 3, defaultReps: 15, defaultWeight: 20 },
      { name: "Cable Hip Abduction",                   defaultSets: 3, defaultReps: 15, defaultWeight: 20 },
      { name: "Cable Hip Extension",                   defaultSets: 3, defaultReps: 15, defaultWeight: 25 },
      { name: "Cable Pull-Through",                    defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Cable Romanian Deadlift",               defaultSets: 3, defaultReps: 10, defaultWeight: 60 },
      { name: "Cable Donkey Kick",                     defaultSets: 3, defaultReps: 15, defaultWeight: 20 },
      { name: "Cable Standing Hip Abduction",          defaultSets: 3, defaultReps: 15, defaultWeight: 15 },
      { name: "Cable Sumo Squat",                      defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Cable Lateral Walk",                    defaultSets: 3, defaultReps: 20, defaultWeight: 10 },
      { name: "Cable Glute Bridge",                    defaultSets: 3, defaultReps: 15, defaultWeight: 30 },
    ],
    barbell: [
      { name: "Barbell Hip Thrust",                    defaultSets: 4, defaultReps: 10, defaultWeight: 135 },
      { name: "Barbell Glute Bridge",                  defaultSets: 3, defaultReps: 15, defaultWeight: 95 },
      { name: "Barbell Romanian Deadlift",             defaultSets: 3, defaultReps: 10, defaultWeight: 155 },
      { name: "Barbell Sumo Deadlift",                 defaultSets: 3, defaultReps: 6,  defaultWeight: 185 },
      { name: "Barbell Good Morning",                  defaultSets: 3, defaultReps: 10, defaultWeight: 95 },
      { name: "Barbell Back Squat (Wide Stance)",      defaultSets: 3, defaultReps: 8,  defaultWeight: 165 },
      { name: "Barbell Step-Up",                       defaultSets: 3, defaultReps: 10, defaultWeight: 85 },
      { name: "Barbell Bulgarian Split Squat",         defaultSets: 3, defaultReps: 8,  defaultWeight: 65 },
      { name: "Barbell Single-Leg RDL",                defaultSets: 3, defaultReps: 8,  defaultWeight: 65 },
      { name: "Barbell Frog Pump",                     defaultSets: 3, defaultReps: 20, defaultWeight: 65 },
    ],
    dumbbell: [
      { name: "Dumbbell Hip Thrust",                   defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Dumbbell Glute Bridge",                 defaultSets: 3, defaultReps: 15, defaultWeight: 40 },
      { name: "Dumbbell Romanian Deadlift",            defaultSets: 3, defaultReps: 10, defaultWeight: 50 },
      { name: "Dumbbell Single-Leg RDL",               defaultSets: 3, defaultReps: 10, defaultWeight: 35 },
      { name: "Dumbbell Sumo Squat",                   defaultSets: 3, defaultReps: 12, defaultWeight: 50 },
      { name: "Dumbbell Step-Up",                      defaultSets: 3, defaultReps: 12, defaultWeight: 30 },
      { name: "Dumbbell Bulgarian Split Squat",        defaultSets: 3, defaultReps: 10, defaultWeight: 30 },
      { name: "Dumbbell Curtsy Lunge",                 defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { name: "Dumbbell Kickback (Kneeling)",          defaultSets: 3, defaultReps: 15, defaultWeight: 10 },
      { name: "Dumbbell Frog Pump",                    defaultSets: 3, defaultReps: 20, defaultWeight: 25 },
    ],
    smith: [
      { name: "Smith Machine Hip Thrust",              defaultSets: 4, defaultReps: 10, defaultWeight: 135 },
      { name: "Smith Machine Glute Bridge",            defaultSets: 3, defaultReps: 15, defaultWeight: 95 },
      { name: "Smith Machine Romanian Deadlift",       defaultSets: 3, defaultReps: 10, defaultWeight: 135 },
      { name: "Smith Machine Sumo Squat",              defaultSets: 3, defaultReps: 10, defaultWeight: 135 },
      { name: "Smith Machine Bulgarian Split Squat",   defaultSets: 3, defaultReps: 10, defaultWeight: 75 },
      { name: "Smith Machine Step-Up",                 defaultSets: 3, defaultReps: 12, defaultWeight: 85 },
      { name: "Smith Machine Good Morning",            defaultSets: 3, defaultReps: 10, defaultWeight: 85 },
      { name: "Smith Machine Single-Leg RDL",          defaultSets: 3, defaultReps: 10, defaultWeight: 65 },
      { name: "Smith Machine Donkey Kick",             defaultSets: 3, defaultReps: 15, defaultWeight: 45 },
      { name: "Smith Machine Frog Pump",               defaultSets: 3, defaultReps: 20, defaultWeight: 65 },
    ],
    machine: [
      { name: "Hip Thrust Machine",                    defaultSets: 4, defaultReps: 12, defaultWeight: 120 },
      { name: "Hip Abduction Machine",                 defaultSets: 3, defaultReps: 15, defaultWeight: 80 },
      { name: "Hip Extension Machine",                 defaultSets: 3, defaultReps: 15, defaultWeight: 60 },
      { name: "Glute Kickback Machine",                defaultSets: 3, defaultReps: 15, defaultWeight: 50 },
      { name: "Leg Press (Feet High & Wide)",          defaultSets: 3, defaultReps: 10, defaultWeight: 180 },
      { name: "Reverse Hyper Machine",                 defaultSets: 3, defaultReps: 15, defaultWeight: 50 },
      { name: "Seated Hip Abduction Machine",          defaultSets: 3, defaultReps: 15, defaultWeight: 70 },
      { name: "Standing Hip Abduction Machine",        defaultSets: 3, defaultReps: 15, defaultWeight: 50 },
      { name: "Glute Ham Raise Machine",               defaultSets: 3, defaultReps: 10, defaultWeight: 0, note: "Bodyweight" },
      { name: "Cable Hip Thrust (Machine Attachment)", defaultSets: 3, defaultReps: 12, defaultWeight: 80 },
    ],
  },
};
